#!/bin/bash
#PBS -q normal
#PBS -l nodes=32:ppn=8:native
#PBS -l walltime=0:30:00
#PBS -N hdf5bench
#PBS -o hdf5bench.out 
#PBS -e hdf5bench.err 
#PBS -M zonca@deepspace.ucsb.edu
#PBS -m abe
#PBS -V
# Start of user commands - comments start with a hash sign (#)

cd /home/zonca/p/dev/hdf5-bench/bench/build

for stripes in 16 32 64 128
do
    mpirun_rsh -np 256 -hostfile $PBS_NODEFILE ./h5_bench $stripes &> log/rwtest_$stripes.log 
done
